[package]
name = "models_database"
version = "0.1.0"
edition = "2024"

[lib]
name = "models_database"
path = "src/lib.rs"

[[bin]]
name = "models_database"
path = "src/main.rs"

[dependencies]
diesel = { version = "2.2", features = ["sqlite", "r2d2", "chrono", "serde_json"] }
libsqlite3-sys = { version = "0.26", features = ["bundled"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dotenvy = "0.15"
chrono = "0.4.35"

diesel_migrations = "2.1"
<<<<<<< HEAD
anyhow = "1.0"
=======
>>>>>>> 988e83801efc0fc0d06d0d1387e6971d75698051

uuid = { version = "1.3", features = ["v4", "serde"] }
shared_config = { path = "../shared_config" }

shared_config={path="../shared_config"}


